# This is the final and correct configuration file.
# Please copy and paste this content exactly as it is.

backend:
  name: git-gateway
  branch: main

# Where to store uploaded media
media_folder: "docs/public/uploads"
# The public path for accessing uploaded media
public_folder: "/uploads"

# Content collections
collections:
  - name: "project"
    label: "Projects"
    folder: "docs/src/content/docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Header Image", name: "image", widget: "image", required: false }
      - { label: "Download File", name: "file", widget: "file", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

