backend:
  name: github
  repo: peditx/starlight-theme-rapide
  branch: main
  # This auth_type is crucial for the direct GitHub login flow
  auth_type: implicit
  app_id: Ov23liMQ36VXRPwraTVC

# The media folder and public folder are for uploads
media_folder: 'docs/public/uploads'
public_folder: '/uploads'

# This is our collection of projects
collections:
  - name: 'projects' # A unique name for the collection
    label: 'Projects' # How it appears in the UI
    folder: 'docs/src/content/docs' # The folder to save files to
    create: true # Allow users to create new documents in this collection
    # The fields for each document in this collection
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }

