backend:
  name: github
  repo: peditx/starlight-theme-rapide
  branch: main

media_folder: "docs/public/uploads"

collections:
  - name: "project"
    label: "Projects"
    folder: "docs/src/content/docs"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
