backend:
  name: github
  repo: peditx/starlight-theme-rapide  # ریپوی خودت
  branch: main
  auth_type: token
  token: "{{ env.YOUR_GITHUB_PERSONAL_ACCESS_TOKEN }}"  # ← Secret واقعی تو

media_folder: "docs/public/uploads"
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "docs/src/content/docs"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
