backend:
  name: github
  repo: peditx/starlight-theme-rapide
  branch: main
  auth_type: implicit
  app_id: YOUR_GITHUB_CLIENT_ID
  base_url: https://auth.decapcms.org

media_folder: "docs/public/uploads"
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "docs/src/content/docs"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
